{
    'name': 'EduOdoo - Sistema de Gestión Académica',
    'version': '1.0.0',
    'category': 'Education',
    'summary': 'Sistema Integral de Gestión para una Academia de Cursos',
    'author': 'EduOdoo Development Team',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/sequence_views.xml',
        'views/curso_views.xml',
        'views/alumno_views.xml',
        'views/sesion_views.xml',
        'views/clases_views.xml',
        'views/profesor_views.xml',
        'views/matricula_views.xml',
        'views/facturacion_views.xml',
        'views/asistencia_views.xml',
        'views/menu_views.xml',
        'reports/sesion_report.xml',
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
}
